# Movies Analysis

In [ ]:
### Prequisties
import warnings

import matplotlib.pyplot as plt
import pandas as pd
warnings.filterwarnings('ignore')
plt.style.use('fivethirtyeight')
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', 50)

In [2]:
movies = pd.read_csv("archive/Movie_Movies.csv", low_memory=False)
genres = pd.read_csv("archive/Movie_Genres.csv", low_memory=False)
ratings = pd.read_csv("archive/Movie_AdditionalRating.csv", low_memory=False)

In [3]:
movies.head()

,Awards,Country,DVD,Director,Language,Plot,Poster,Production,Rated,Released,Runtime,Title,Type,Website,Year,imdbID,imdbRating,imdbVotes
0,NaN,USA,NaN,Rose Cummings,English,Rachel constantly hears her baby cry from the ...,NaN,NaN,NaN,26 Apr 2012,20 min,Baby's Breath,movie,NaN,2012,tt2268369,NaN,NaN
1,NaN,USA,NaN,James Byrne,NaN,The struggle against unfortunate circumstances...,NaN,NaN,NaN,NaN,9 min,Winter Trees,movie,NaN,2008,tt1560760,NaN,NaN
2,NaN,USA,NaN,Dimitri Buchowetzki,NaN,NaN,NaN,NaN,NaN,27 Mar 1926,50 min,The Crown of Lies,movie,NaN,1926,tt0016750,NaN,NaN
3,NaN,USA,NaN,Julia Hechler,English,"A Gift introduces Samuel Green, Washington Sta...",NaN,NaN,NaN,27 May 2013,2 min,A Gift,movie,NaN,2013,tt3405286,NaN,NaN
4,NaN,Sri Lanka,NaN,Udara Siriruwan,Sinhalese,NaN,NaN,NaN,NaN,20 Mar 2014,23 min,Journey,movie,NaN,2014,tt3816698,NaN,NaN

In [4]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178687 entries, 0 to 178686
Data columns (total 18 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Awards      20340 non-null   object
 1   Country     165998 non-null  object
 2   DVD         15949 non-null   object
 3   Director    151353 non-null  object
 4   Language    153196 non-null  object
 5   Plot        97476 non-null   object
 6   Poster      48414 non-null   object
 7   Production  16446 non-null   object
 8   Rated       23906 non-null   object
 9   Released    116974 non-null  object
 10  Runtime     119497 non-null  object
 11  Title       178686 non-null  object
 12  Type        178686 non-null  object
 13  Website     6747 non-null    object
 14  Year        178686 non-null  object
 15  imdbID      178686 non-null  object
 16  imdbRating  62073 non-null   float64
 17  imdbVotes   62029 non-null   object
dtypes: float64(1), object(17)
memory usage: 24.5+ MB

In [5]:
movies.describe()

         imdbRating
count  62073.000000
mean       6.416236
std        1.360472
min        1.000000
25%        5.600000
50%        6.500000
75%        7.300000
max       10.000000

In [6]:
movies.sort_values("imdbRating", ascending=False)

,Awards,Country,DVD,Director,Language,Plot,Poster,Production,Rated,Released,Runtime,Title,Type,Website,Year,imdbID,imdbRating,imdbVotes
147179,NaN,Greece,NaN,Leonard Thimo,"Greek, English",NaN,NaN,NaN,NaN,01 Mar 2014,NaN,The Twenty-Eight Hits for Laughs 4th Season,movie,NaN,2014,tt3565880,10.0,7
39888,NaN,USA,NaN,NaN,English,NaN,https://images-na.ssl-images-amazon.com/images...,NaN,NaN,09 Dec 2016,6 min,Fate of Revenge,movie,NaN,2016,tt6323164,10.0,6
90847,NaN,USA,NaN,Ray Ellingsen,English,Reach your full career potential by developing...,https://images-na.ssl-images-amazon.com/images...,NaN,NaN,01 Sep 2007,60 min,Skills for Actors: Voice Skills,movie,NaN,2007,tt1260398,10.0,6
124395,1 win.,USA,NaN,Lukas Hassel,English,The event on a young boy's birthday has conseq...,https://images-na.ssl-images-amazon.com/images...,NaN,NaN,10 Aug 2017,NaN,"The Son, the Father",movie,NaN,2017.0,tt6860566,10.0,6
30948,NaN,Australia,NaN,Neil Mansfield,NaN,A pretty young lady rides her old blue bicycle...,NaN,NaN,NaN,NaN,6 min,The Girl in the Sun,movie,NaN,2013,tt2705624,10.0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177194,1 nomination.,USA,NaN,Paula Saslow,Spanish,NaN,https://images-na.ssl-images-amazon.com/images...,NaN,NaN,10 Jan 2016,NaN,Diablo,movie,NaN,2016,tt3813570,NaN,NaN
177199,NaN,"China, South Korea",17 May 2016,Kim Daewoo,English,NaN,NaN,A24 Films,NaN,NaN,NaN,The Witch,movie,http://thewitch-movie.com/,2016,tt5092276,NaN,NaN
177387,NaN,USA,30 May 2017,Jess Carson,English,Quinn and Julie connect after their respective...,NaN,Open Road Films,NaN,NaN,NaN,Collide,movie,http://collidefilm.com/,2017,tt2834052,NaN,NaN
177395,NaN,UK,NaN,Iannis Aliferis,English,A career soldier returns to his loving and emp...,https://images-na.ssl-images-amazon.com/images...,Petit Film,NaN,02 Dec 2017,5 min,Raw,movie,NaN,2017,tt7650514,NaN,NaN
177452,NaN,USA,17 Oct 2017,NaN,English,NaN,NaN,Roadside Attractions,NaN,31 Aug 2017,NaN,Lady Macbeth,movie,http://www.ladymacbethfilm.com/,2017,tt7318300,NaN,NaN

In [7]:
movies.isnull().sum()

Awards        158347
Country        12689
DVD           162738
Director       27334
Language       25491
Plot           81211
Poster        130273
Production    162241
Rated         154781
Released       61713
Runtime        59190
Title              1
Type               1
Website       171940
Year               1
imdbID             1
imdbRating    116614
imdbVotes     116658
dtype: int64

In [8]:
movies.Director.value_counts().head(10)

Jim Powers                             151
D.W. Griffith                          101
Lewin Fitzhamon                         95
Dave Fleischer                          94
Al Christie                             90
Georges Méliès                          86
Gilbert M. 'Broncho Billy' Anderson     85
Quasarman                               84
Kevin Dunn                              83
Nica Noelle                             78
Name: Director, dtype: int64

In [6]:
director_counts = movies['Director'].value_counts().head(10).to_frame().reset_index()
director_counts.columns = ['Director','NumberOfMoviesProduced']
director_counts.style.hide_index()

In [10]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92016 entries, 0 to 92015
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    92016 non-null  int64
 1   Rating        92016 non-null  object
 2   RatingSource  92016 non-null  object
 3   imdbID        92016 non-null  object
dtypes: int64(1), object(3)
memory usage: 2.8+ MB

In [11]:
ratings.drop('Unnamed: 0', axis=1, inplace=True)

movies_rating = (ratings
                  .set_index("imdbID")
                  .join(movies.set_index("imdbID"),
                        how="left")
                 )

In [13]:
movies_rating.head()

,Rating,RatingSource,Awards,Country,DVD,Director,Language,Plot,Poster,Production,Rated,Released,Runtime,Title,Type,Website,Year,imdbRating,imdbVotes
imdbID,,,,,,,,,,,,,,,,,,,
tt0000012,7.4/10,Internet Movie Database,NaN,France,NaN,"Auguste Lumière, Louis Lumière",NaN,A train arrives at La Ciotat station.,https://images-na.ssl-images-amazon.com/images...,NaN,NOT RATED,25 Jan 1896,1 min,The Arrival of a Train,movie,NaN,1896,7.4,"7,930"
tt0000035,5.4/10,Internet Movie Database,NaN,France,NaN,Georges Méliès,NaN,NaN,http://ia.media-imdb.com/images/M/MV5BYWY1Mjc5...,NaN,NaN,NaN,NaN,Watering the Flowers,movie,NaN,1896,5.4,33
tt0000054,5.8/10,Internet Movie Database,NaN,France,NaN,Georges Méliès,NaN,Very little is known of this lost Georges Meli...,https://images-na.ssl-images-amazon.com/images...,NaN,NaN,NaN,NaN,A Merry-Go-Round,movie,NaN,1896,5.8,12
tt0000068,4.3/10,Internet Movie Database,NaN,France,NaN,Georges Méliès,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unloading the Boat,movie,NaN,1896,4.3,12
tt0000079,4.4/10,Internet Movie Database,NaN,France,NaN,Georges Méliès,NaN,NaN,http://ia.media-imdb.com/images/M/MV5BOTUyYjgz...,NaN,NaN,NaN,NaN,La gare Saint-Lazare,movie,NaN,1896,4.4,14